version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: liftpassadmin
      MYSQL_PASSWORD: l1ftp4ss4dm1n
    volumes:
      - mariadb-data:/var/lib/mysql
      - ../database/mariadb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      retries: 3
      timeout: 30s

  postgres:
    image: postgres:latest
    shm_size: 128mb
    environment:
      POSTGRES_DB: lift_pass
      POSTGRES_USER: liftpassadmin
      POSTGRES_PASSWORD: l1ftp4ss4dm1n
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../database/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      retries: 3
      timeout: 30s

volumes:
  mariadb-data:
  postgres-data:
