version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: liftpassadmin
      MYSQL_PASSWORD: l1ftp4ss4dm1n
    volumes:
      - data:/var/lib/mysql
      - ../database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      retries: 3
      timeout: 30s

volumes:
  data:
