version: '3.8'

services:
  postgres:
    image: postgres:latest
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: admin
      POSTGRES_DB: lift_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../database/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U admin -d lift_pass
      interval: 5s
      retries: 3
      timeout: 30s

volumes:
  postgres-data:
