name: Main pipeline
on:
  push:
    branches:
      - "main"

# Ensures that only a single job or workflow using the same concurrency group (branch) will run at a time
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/job-tests.yml
