name: PR pipeline
on:
  pull_request:
    branches:
      - "main"
    types: [synchronize, opened, reopened, ready_for_review]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures that only a single job or workflow using the same concurrency group (branch) will run at a time
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  tests:
    name: PR pipeline
    uses: ./.github/workflows/job-tests.yml
    secrets: inherit
